
insert into role (id, name) values(1, 'ROLE_USER');
insert into role (id, name) values(2, 'ROLE_ADMIN');
insert into role (id, name) values(3, 'ROLE_SUPERADMIN');

insert into uzer (id, first_name, last_name, email, password, date) values (1, 'Eleonora', 'Linsay', 'elinsay0@twitter.com', 'mHIegKs', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (2, 'Shandeigh', 'Silwood', 'ssilwood1@instagram.com', '7BlfcT6', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (3, 'Sherwynd', 'Valde', 'svalde2@hao123.com', 'pXzl6FJ6', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (4, 'Deerdre', 'Checcucci', 'dcheccucci3@a8.net', 'rmqdVchYv', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (5, 'Clarinda', 'Eyam', 'ceyam4@homestead.com', 'uvkrcjyRZSV', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (6, 'Delbert', 'Danton', 'ddanton5@alibaba.com', 'tHE6E8FxOM', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (7, 'Gun', 'Schott', 'gschott6@ihg.com', 'fI9K13', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (8, 'Ernest', 'Mordecai', 'emordecai7@yale.edu', 'GkawyTUsl7', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (9, 'Taddeo', 'Whitwham', 'twhitwham8@squidoo.com', 'YJ4cLUZRA8', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (10, 'Harley', 'Fenny', 'hfenny9@jalbum.net', 'GVYdTQe8', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (11, 'Zachariah', 'Schulze', 'zschulzea@cmu.edu', '1xtfU6HK4', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (12, 'Felecia', 'Thomelin', 'fthomelinb@simplemachines.org', 'BuzZX9F', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (13, 'Rennie', 'Kundert', 'rkundertc@ezinearticles.com', 'zhNbZMVJH4bV', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (14, 'Kin', 'Cuxson', 'kcuxsond@tumblr.com', 'pNBQl25x', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (15, 'Ainsley', 'Stillman', 'astillmane@imageshack.us', 'RlAki5', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (16, 'Dannye', 'Scough', 'dscoughf@cocolog-nifty.com', 'Lx8Zzir3W9K', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (17, 'Robina', 'Hymers', 'rhymersg@irs.gov', 'qc7IoFTI', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (18, 'Maureene', 'Harland', 'mharlandh@live.com', '1ZmGoY', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (19, 'Tobi', 'Janes', 'tjanesi@google.it', 'eiJuQlNu', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (20, 'Rolando', 'Cardoo', 'rcardooj@usnews.com', 'cHjO4MlTWcy7', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (21, 'Bernarr', 'Beauly', 'bbeaulyk@lulu.com', '3ywa5G', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (22, 'Lettie', 'D''eath', 'ldeathl@dailymotion.com', '2VlANn3RH', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (23, 'Camilla', 'Bointon', 'cbointonm@storify.com', 'Eq13ArU', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (24, 'Alaine', 'Olligan', 'aolligann@google.co.jp', '73F2dr2Kyr', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (25, 'Myrna', 'Moring', 'mmoringo@merriam-webster.com', 'pPhI4j', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (26, 'Celia', 'Dunnett', 'cdunnettp@scientificamerican.com', 'RbCiGmj5qR', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (27, 'Allard', 'Winterflood', 'awinterfloodq@trellian.com', 'CvLIKv317', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (28, 'Godiva', 'Andrassy', 'gandrassyr@yellowbook.com', 'H6AtEK3SPkT', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (29, 'Hort', 'Cattrall', 'hcattralls@networksolutions.com', 'tBWhPUWAkDwf', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (30, 'Bernette', 'Skains', 'bskainst@paypal.com', 'cqwOdcc', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (31, 'Arabela', 'Klisch', 'aklischu@github.io', 'VzPNLR', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (32, 'Brandy', 'de Clerc', 'bdeclercv@nifty.com', 'hMuaGDzWnG', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (33, 'Godiva', 'Penley', 'gpenleyw@wikia.com', 'w2N2txOrp', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (34, 'Avrom', 'Tolworthy', 'atolworthyx@sphinn.com', 'IfAqTZ4eu', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (35, 'Hermon', 'Furmenger', 'hfurmengery@time.com', 'BEcKBGtx5RDF', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (36, 'Arielle', 'Roughley', 'aroughleyz@studiopress.com', '4FiBM6yw', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (37, 'Hyatt', 'Albery', 'halbery10@telegraph.co.uk', 'wBRiue9WJ', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (38, 'Dolorita', 'Maciejewski', 'dmaciejewski11@house.gov', 'TLq49qIeq', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (39, 'Thorpe', 'Vigers', 'tvigers12@foxnews.com', 'bgUsFN', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (40, 'Cyndy', 'Dumberrill', 'cdumberrill13@cyberchimps.com', 'rX8sBF', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (41, 'Cherry', 'Tarzey', 'ctarzey14@alibaba.com', 'al4df9S1KXxy', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (42, 'Delilah', 'Shearn', 'dshearn15@e-recht24.de', 'o1vZ5tInye', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (43, 'Leshia', 'Iacoviello', 'liacoviello16@arizona.edu', '8NFQhlXmtVr', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (44, 'Babara', 'Gilphillan', 'bgilphillan17@squarespace.com', 'oRiJ9S', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (45, 'Danika', 'Bartolomeoni', 'dbartolomeoni18@facebook.com', '5n1O78GjL', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (46, 'Bobine', 'Ruusa', 'bruusa19@google.es', 'eI6ROaU4HY', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (47, 'Naomi', 'Wignall', 'nwignall1a@boston.com', 'DoLckte9', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (48, 'Karlik', 'Murrey', 'kmurrey1b@privacy.gov.au', '0uGqwkzp', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (49, 'Felisha', 'McKenny', 'fmckenny1c@japanpost.jp', 'OT2oykQh4j', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (50, 'Selene', 'Whitfeld', 'swhitfeld1d@ucsd.edu', 'chnNXODev', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (51, 'Sherm', 'MacCafferky', 'smaccafferky1e@reuters.com', 'EEHUcM', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (52, 'Lincoln', 'Mazzey', 'lmazzey1f@icq.com', 'ft83hBuEXi9', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (53, 'Lucius', 'Starmont', 'lstarmont1g@umich.edu', 'tkaga5jg', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (54, 'Woodman', 'Zwicker', 'wzwicker1h@bloglovin.com', 'dMFijEeLhI', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (55, 'Daisi', 'Jewkes', 'djewkes1i@lycos.com', 'GHvLVI1', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (56, 'Bernarr', 'Mildenhall', 'bmildenhall1j@elegantthemes.com', '67MGqq2Gwv', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (57, 'Knox', 'Grocott', 'kgrocott1k@scientificamerican.com', 'vkzsQgzJc', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (58, 'Piper', 'Pietersen', 'ppietersen1l@mozilla.org', '0XaOZcE', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (59, 'Sherill', 'O''Daly', 'sodaly1m@google.co.uk', 'zoE3z52', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (60, 'Carolin', 'McFayden', 'cmcfayden1n@java.com', '46IdMK', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (61, 'Florenza', 'Giacopetti', 'fgiacopetti1o@hubpages.com', 'AhnnMO2dgfL', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (62, 'Jdavie', 'Bough', 'jbough1p@bloglines.com', '4RkjWjJq9rn', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (63, 'Thebault', 'Vasenkov', 'tvasenkov1q@miitbeian.gov.cn', 'e7xrg5rDBaPh', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (64, 'Boniface', 'Folcarelli', 'bfolcarelli1r@blogs.com', 'XVVF0c8sFW0B', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (65, 'Delphinia', 'Peever', 'dpeever1s@census.gov', 'OgDATTQGD', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (66, 'Beth', 'Rosenbusch', 'brosenbusch1t@ezinearticles.com', 'xEkv67m9', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (67, 'Phil', 'Belderson', 'pbelderson1u@yandex.ru', 'sNdDAzu', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (68, 'Thorn', 'Gasquoine', 'tgasquoine1v@cafepress.com', 'aiWTh4SLN', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (69, 'Ricki', 'Marrett', 'rmarrett1w@uol.com.br', 'C7j3iLy9S', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (70, 'Marcia', 'Lipp', 'mlipp1x@marketwatch.com', 'zjs83bJgK', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (71, 'Sammy', 'Lewtey', 'slewtey1y@jigsy.com', 'BUxXbYo', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (72, 'Peri', 'Steanyng', 'psteanyng1z@indiatimes.com', 'YTKGlnBDg1Td', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (73, 'Berty', 'Houten', 'bhouten20@irs.gov', '98OyEzocUZ', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (74, 'Terrye', 'Broy', 'tbroy21@mac.com', 'kEGH9oV', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (75, 'Dodie', 'Golton', 'dgolton22@imgur.com', 'JZY3z2L', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (76, 'Candi', 'Beviss', 'cbeviss23@theglobeandmail.com', 'weuoVmh', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (77, 'Brennan', 'Guerre', 'bguerre24@huffingtonpost.com', '9vZPOE8', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (78, 'Leif', 'Messenbird', 'lmessenbird25@patch.com', 'GwXDLa', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (79, 'Farrah', 'Loseby', 'floseby26@tuttocitta.it', 'jhS4C8SOz', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (80, 'Puff', 'Barniss', 'pbarniss27@wordpress.org', 'rfRLPYV', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (81, 'Del', 'Bladon', 'dbladon28@diigo.com', 'htV5bApfIVU', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (82, 'Shanon', 'Pegden', 'spegden29@elegantthemes.com', 'uvQCrprU1Sj', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (83, 'Gaby', 'Bromley', 'gbromley2a@upenn.edu', '6oGWI2', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (84, 'Christean', 'Bungey', 'cbungey2b@de.vu', 'vePmY6', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (85, 'Amory', 'Keslake', 'akeslake2c@gravatar.com', 'TSAygi', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (86, 'Charlean', 'Martellini', 'cmartellini2d@gmpg.org', 'GNuGk3yr', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (87, 'Annamaria', 'Taplin', 'ataplin2e@upenn.edu', 'oamf1v6A', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (88, 'Dar', 'Clubley', 'dclubley2f@illinois.edu', 'ngyGwewW', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (89, 'Christiana', 'McAlester', 'cmcalester2g@gnu.org', 'XlCiBeaXkw', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (90, 'Magdaia', 'Richarz', 'mricharz2h@godaddy.com', 'MbtX04r3uF', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (91, 'Madelaine', 'MacCartney', 'mmaccartney2i@hao123.com', 'DYMseZerV', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (92, 'Vanny', 'Kubiak', 'vkubiak2j@gov.uk', 'VQxuibb65m', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (93, 'Nelli', 'Tierney', 'ntierney2k@merriam-webster.com', 'YrkSCPC', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (94, 'Claire', 'Lampaert', 'clampaert2l@cmu.edu', 'shfatI', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (95, 'Marysa', 'Von Der Empten', 'mvonderempten2m@cbsnews.com', 't8uS2R4vK', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (96, 'Barnett', 'Mingauld', 'bmingauld2n@myspace.com', 'Xy9XyK', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (97, 'Cort', 'McAreavey', 'cmcareavey2o@shareasale.com', '0bxoOVrI3h', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (98, 'Valeda', 'Rodman', 'vrodman2p@usatoday.com', '5H9Dl4Cg2', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (99, 'Bertha', 'Angrock', 'bangrock2q@businesswire.com', 'A6Pqkakh', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (100, 'Chrystal', 'Imrie', 'cimrie2r@purevolume.com', 'K0Dz9nQm', '2020/12/30');
insert into uzer (id, first_name, last_name, email, password, date) values (101, 'Tim', 'Yak', 'admin@gmail.com', '123qweasd', '2020/12/30');

/*
After user and role
*/
INSERT INTO public.uzer_roles (user_id, roles_id) VALUES (1, 1);
INSERT INTO public.uzer_roles (user_id, roles_id) VALUES (1, 2);
INSERT INTO public.uzer_roles (user_id, roles_id) VALUES (101, 1);
INSERT INTO public.uzer_roles (user_id, roles_id) VALUES (101, 2);
INSERT INTO public.uzer_roles (user_id, roles_id) VALUES (101, 3);


